### ISSUE TITLE
Files with external memory fail

### ISSUE THREAD

**Issue by Varzk-Krethalen** [encedo/hex2dfu#3]
I have a 3,700kb hex file I need to convert, but the tool crashes on reaching line 405:
```
while ( fgets (oneline, sizeof(oneline), inFile) != NULL ) {
```
This appears to be because of inFile being invalid - I'm not especially skilled with C++, so do you know of any way this could be fixed?

**Comment by encedo** [comment]
Hi

Do not worry, you are not skilled in C++. Just send me a test file (e.g. wetransfer) I will fix it.

Chris

**Comment by Varzk-Krethalen** [comment]
https://we.tl/t-xjfcqlfgWh
I have sucessfully tested this file with the ST tools.
Thanks!

**Comment by encedo** [comment]
Hi

Source code updated (version raised to 1.4). 

The issue was not the size of the input file but the fact, input file had data out of the STM32 Flash memory address. In your case, you have external RAM at address 0xd0000000 and in the input hex file, there is a section to fill it with zeros. 

Added the default value of the possible address in Flash memory for STM32 (possible to change by new parameter '-E').

Let me know how it works.

Chris

**Comment by Varzk-Krethalen** [comment]
Thanks for the quick fix! 
Sorry, I didn't think about the external memory being an issue.
The conversion worked fine, though I cannot test on hardware for the moment.
(Issue title corrected)
